### PR TITLE
Added HealNodeNetwork function

### PR DESCRIPTION
**Pull request by havivi86**
Added HealNodeNetwork to the node class.
This function helps to set up the node neighbours correctly, and setting the associated nodes in all association groups as return route. This is needed when setting up new sensor where you want it to send it's status directly to another node in the network.

### CODE REVIEW

**Comment by roblans** [comment]
Changed merged, new NuGet package published.

**Comment by richardthombs** [comment]
@havivi86 Hi, can you explain the thinking behind this algorithm? I don't use association groups at all, will this still work for my network do you think?

Do you happen to know if ZWave takes care of this itself at all? Eg, if I move a node around my house, will it update neighbors by itself, or do I have to force it?

**Comment by havivi86** [comment]
Hi @richardthombs . 
You asked several questions. First, the algorithm came from the openZWave library. The motivation is this - 
I bought 2 ZWave devices - door sensor and serine. I tried to make the sensor talk directly to the serine without success for long time, and I had no idea why. After long investigation, I learned the concept of the return route. Basically, it tells the device (my sensor in my case) which devices it can communicate with directly without the controller. openZWave do this assignment in "heal" network function, so I took the idea. it fixed my problem.
about you other questions - I'm not sure if ZWave take care of it by itself as part of the protocol. I think I'll add daily "fix" to my network. The fact is that my device couldn't communicate with the siren for long time until I did this trick (and both devices set on my desk).
Also, even if you don't use association, I believe you can still benefit from this "heal" as it forcing refresh of neighbors. I'm not expert and I might be wrong, but I believe it can improve the communication between devices and it ca't do harm.

**Comment by richardthombs** [comment]
Thank you, I'll try it out!

**Pull request merged**
